[package]
name = "bgutil-rs"
version = "0.1.0"
authors = ["Patrick MARIE <pm@mkz.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cassandra-cpp = "0.15.1"
chrono = "0.4"
clap = "2.33.3"
regex = "1.4.3"
